name: mealmaster
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  shared_preferences: ^2.0.8
  adaptive_theme: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^0.13.4
  url_launcher: ^6.0.9  

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png


  
